services:
  app:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/var/www
    networks:
      - blog-frontend-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8

networks:
  blog-frontend-network:
